Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 20/07/2020
Var
// Seção de Declarações das variáveis 
procedimento soma(A, B : inteiro)
inicio
Escreva("A soma deu: ", A + B)

fimprocedimento

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Soma(8, 5)

Fimalgoritmo